name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"
      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          java-package: jdk
          architecture: x64

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm install
      - run: npm run build
      - run: npm run lint:ts
      - run: cd example && npm install
      - run: npm run ci:compile:android
      - run: npm run build

  test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: ^12.0
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12.x"

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Cache Pods modules
        uses: actions/cache@v2
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - run: gem install cocoapods
      - run: npm install
      - run: npm run build
      - run: npm run lint:ts
      - run: cd example && npm install && npm run install:pods
      - run: npm run ci:compile:ios
      - run: npm run build

  publish:
    needs:
      - test-android
      - test-ios
    runs-on: ubuntu-latest
    steps:
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm install
      - run: npm run build

      - name: NPM Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          check-version: true
          dry-run: true
